- hosts: "{{ target_hosts | default('blank-rhel') }}"
  gather_facts: True
  become: yes
  become_user: root
  tasks:
  - name: Install {{ pkg_name }}
    package:
       name: "{{ pkg_name }}"
       state: present
