- hosts: "{{ target_hosts | default('blank-rhel') }}"
  become: yes
  become_user: root
  tasks:
  - name: "{{ pkg_name }} will be {{ pkg_state }}"
    yum:
       name: "{{ pkg_name }}"
       state: "{{ pkg_state }}"
